---
# source path
source: ./source

# target path
target: ./target

suffix: 
  excludes: 
    - .torrent
  includes:
    - .mp4
    - .mkv

# rules for moving new files
rules:
  - keyword: 'example'
    folder: 'test'
